# Dev Environment.

teamcode:
  home: /Users/chiang/my-temp/teamcode-home
  artifacts-dir: /Users/chiang/my-temp/teamcode-home/data/ci/artifacts
  #external-url: http://teamcode.example.com
  external-url: http://localhost:8080

  #security:
  #  ip-white-list: 127.0.0.12, 10.10.11.12

  attachments:
    downloads:
      max-files: 100

  ticket:
    eanbled: true

  sync:
    permission: true

mail:
  enabled: true
  host: smtp.mailgun.org
  port: 587
  from: '***'
  from-name: '팀코드'
  username: '***'
  password: '***'
  test-connection: true
  properties:
    mail:
      smtp:
        connecttimeout: 5000
        timeout: 3000
        writetimeout: 5000

subversion:
  version: 1.9
  realm: TeamCode Managed Subversion Repository
  repository:
    root: ''

container:
  # Connector Protocol. 'HTTP/1.1' or 'AJP/1.3'
  protocol: AJP/1.3
  port: 8009

  # time unit -> Minutes
  # default 30 Minutes
  session-timeout: 60


datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:test;MODE=PostgreSQL
  username: ''
  password: ''

  # pooling
  idleMaxAgeInMinutes: 240
  idleConnectionTestPeriodInMinutes: 60
  maxConnectionsPerPartition: 10
  minConnectionsPerPartition: 5
  partitionCount: 2
  acquireIncrement: 5
  statementsCacheSize: 100
  # mysql (SELECT 1), postgresql (SELECT NOW()),
  connectionTestStatement: "SELECT NOW()"

spring:

  http:
    multipart:
      max-file-size: 10MB

  thymeleaf:
    mode: HTML5
    cache: false

  velocity:
    resource-loader-path: file:///Users/chiang/projects/teamcode-server/src/main/resources/templates
    cache: false
    date-tool-attribute: dateTool # Name of the DateTool helper object to expose in the Velocity context of the view.
    number-tool-attribute: numberTool
    expose-session-attributes: true
    #toolbox-config-location: "classpath:toolbox.xml"
  jpa:
    # oracle, mysql, hsql, h2, postgresql (if your dbms is 'MS SQL Server', comment this line and uncomment 'dialect:...' line)
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        default_batch_fetch_size: 4
        jdbc:
          fetch_size: 20
        # for sql server
        #dialect: io.teamcode.common.dialect.AdvancedSqlServerDialect

        # for oracle
        #dialect: io.teamcode.common.dialect.AdvancedOracleDialect

    repositories:
      enabled: true

flyway:
  locations: classpath:flyway/db/postgresql # locations of migrations scripts

logging:
  path: ./logs

  # logger level
  level:
    io:
      teamcode: DEBUG
    org:
      springframework:
        boot.actuate.endpoint.mvc: ERROR
        cache: ERROR
        web: ERROR
        security: ERROR
      hibernate: ERROR
      thymeleaf: DEBUG

---

spring:
  profiles: local

  jpa:
    # oracle, mysql, hsql, h2, postgresql (if your dbms is 'MS SQL Server', comment this line and uncomment 'dialect:...' line)
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: none

teamcode:
  sync:
    permission: false

container:
  # Connector Protocol. 'HTTP/1.1' or 'AJP/1.3'
  protocol: HTTP/1.1
  port: 8080

datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost/teamcode
  username: 'teamcode'
  password: '***'

  # pooling
  idleMaxAgeInMinutes: 240
  idleConnectionTestPeriodInMinutes: 60
  maxConnectionsPerPartition: 10
  minConnectionsPerPartition: 5
  partitionCount: 2
  acquireIncrement: 5
  statementsCacheSize: 100
  # mysql (SELECT 1), postgresql (SELECT NOW()),
  connectionTestStatement: "SELECT NOW()"


logging:

  # logger level
  level:
    org:
      flywaydb: INFO